fixtures:
  repositories:
    'stdlib':
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: '4.24.0'
    'concat':
      repo: git://github.com/puppetlabs/puppetlabs-concat.git
      ref: '4.1.1'
  symlinks:
    'openssl': "#{source_dir}"
