fixtures:
  repositories:
    'stdlib':
      repo: http://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: '4.25.0'
    'concat':
      repo: http://github.com/puppetlabs/puppetlabs-concat.git
      ref: '4.1.0'
  symlinks:
    'openssl': "#{source_dir}"
