---
inherit_gem:
  voxpupuli-test: rubocop.yml

AllCops:
  UseCache: false
Layout/DotPosition:
  Enabled: false
Style/HashLikeCase:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/RescueStandardError:
  Enabled: false

# The following cops fail for Rubocop-1.50
#
Lint/EmptyEnsure:
  Enabled: false
Lint/EnsureReturn:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false
